#### dataset

In [1]:
import pandas as pd

In [ ]:
data1 = pd.read_csv("C:/Users/user/Desktop/BITAmin 15/4_25-2/NLP project/share/bio_papers_dataset.csv")
data2 = pd.read_csv("C:/Users/user/Desktop/BITAmin 15/4_25-2/NLP project/share/df_bio_abstract.csv")
data3 = pd.read_csv("C:/Users/user/Desktop/BITAmin 15/4_25-2/NLP project/share/biological_papers_2020_2025.csv")
data4 = pd.read_csv("C:/Users/user/Desktop/BITAmin 15/4_25-2/NLP project/share/bio_2020_2025_single.csv")

In [ ]:
data1.head()

,title,year,doi,abstract
0,Identification of a neural basis for energy ex...,2025,10.1016/j.neuron.2025.08.021,Given the evolutionary instinct for caloric in...
1,Radiofrequency regulates the BET-mediated path...,2025,10.1016/j.celrep.2025.116238,The human brain represents one of the most com...
2,Genome-wide association meta-analysis of child...,2025,10.1038/s41588-025-02295-y,We performed a genome-wide association meta-an...
3,Elevated EGR1 binding at enhancers in excitato...,2025,10.1186/s12915-025-02357-x,<h4>Background</h4>Brain development and neuro...
4,Polygenic predisposition to transdiagnostic sy...,2025,10.1016/j.pnpbp.2025.111512,<h4>Background</h4>Mood and psychotic disorder...

In [ ]:
data2.head()

,title,abstract
0,Adult and larval photoreceptors use different ...,Although development of the adult Drosophila c...
1,Gap Junction in the Teleost Fish Lineage: Dupl...,Gap junctions are intercellular channels that ...
2,Some Limitations of Public Sequence Data for P...,The GenBank database contains essentially all ...
3,Duplicated rDNA sequences of variable lengths ...,We describe cloned segments of rDNA that conta...
4,Two Clustering Diffusion Patterns Identified f...,This study analyzed the spatio-temporal patter...

In [ ]:
data3.head()

,title,doi,publication_year,journal,authors,abstract
0,Wheat phytase can alleviate the cellular toxic...,https://doi.org/10.5187/jast.2021.e12,2020,NaN,Jeongmin An; Jaiesoon Cho,The objective of this study was to characteriz...
1,Influence of yarn parameters on cotton/kenaf b...,https://doi.org/10.15282/jmes.14.4.2020.26.0600,2020,NaN,S. A. S. Abdullah; Nurul Zuhairah Mahmud Zuhud...,Spinning kenaf fibers into yarns is challengin...
2,Plant Growth Promoting Traits of Phosphate Sol...,https://doi.org/10.4038/jfa.v13i1.5223,2020,NaN,B. C. Walpola; R. H. A. N. Hettiarachchi,Journal of Food and Agriculture is a half year...
3,THE RELATIONSHIP BETWEEN MACROPLASTIC AND LARG...,https://doi.org/10.36713/epra5992,2020,NaN,Anisah Jessica Lee; Zaity Syazwani Mohd Odli; ...,Several locations representing recreational ar...
4,Terms of use of judicial acts for machine lear...,https://doi.org/10.24147/2542-1514.2020.4(4).1...,2020,NaN,Ekaterina Alekseevskaya,The subject of the article is some judicial ac...

In [ ]:
data4.head()

,id,year,title,abstract
0,226554970,2020,Pragmatic Distance in IoT Devices,Stand-alone devices perform their functions wi...
1,219523670,2020,Realizing superior energy storage properties i...,Based on the principle of sustainable developm...
2,237715270,2021,"Rational Design of Perforated Bimetallic (Ni, ...",Highly conductive 3D ordered mesoporous Ni7 S6...
3,248241970,2022,Detection and identification of marine fish mi...,"In this study, DNA barcoding was applied to id..."
4,215816920,2020,An Analysis of Characteristics and Typical Pro...,Type analysis of MOOCs is a basic research. In...

In [ ]:
data1 = data1[['title', 'abstract']]
data2 = data2[['title', 'abstract']]
data3 = data3[['title', 'abstract']]
data4 = data4[['title', 'abstract']]

In [ ]:
data1.shape, data2.shape, data3.shape, data4.shape

((30000, 2), (74, 2), (286592, 2), (300000, 2))

In [ ]:
data = pd.concat([data1, data2, data3, data4], axis=0)

In [ ]:
data['title'].duplicated().any()

np.True_

In [ ]:
data = data.drop_duplicates(subset=['title'], keep='first')

In [ ]:
data['title'].duplicated().any()

np.False_

In [ ]:
data

,title,abstract
0,Identification of a neural basis for energy ex...,Given the evolutionary instinct for caloric in...
1,Radiofrequency regulates the BET-mediated path...,The human brain represents one of the most com...
2,Genome-wide association meta-analysis of child...,We performed a genome-wide association meta-an...
3,Elevated EGR1 binding at enhancers in excitato...,<h4>Background</h4>Brain development and neuro...
4,Polygenic predisposition to transdiagnostic sy...,<h4>Background</h4>Mood and psychotic disorder...
...,...,...
299995,Logic-Depth-Aware Technology Mapping Method fo...,This article proposes a method for generating ...
299996,Linearized Full Duplex Radio-Over-Fiber-Over-S...,This paper proposes a full-duplex Radio-over-F...
299997,Atypical clinical manifestations and genotype-...,Purpose of the study: Analysis of available da...
299998,Dietary interventions for autism spectrum diso...,Autism is a complex spectrum of disorders with...
299999,Brain Abscess of Otorhinolaryngologic Origin: ...,Introduction: Brain abscesses are serious cond...

In [ ]:
data.to_csv('C:/Users/user/Desktop/BITAmin 15/4_25-2/NLP project/merged_dataset.csv', index=False)